-- 코드를 입력하세요
# SELECT DISTINCT a.USER_ID, a.PRODUCT_ID, a.ONLINE_SALE_ID
# FROM ONLINE_SALE AS a INNER JOIN ONLINE_SALE AS b ON a.USER_ID = b.USER_ID AND a.PRODUCT_ID = b.PRODUCT_ID AND NOT a.ONLINE_SALE_ID = b.ONLINE_SALE_ID
# ORDER BY USER_ID,PRODUCT_ID DESC

SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(USER_ID) > 1
ORDER BY USER_ID ,PRODUCT_ID DESC