-- USER_INFO 테이블과 ONLINE_SALE 테이블에서 2021년에 가입한 전체 회원들 중 상품을 구매한 회원수와 상품을 구매한 회원의 비율
WITH SIGN_UP_AT_2021 AS(

    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED LIKE "2021%"

)



SELECT DATE_FORMAT(SALES_DATE,"%Y") AS YEAR,DATE_FORMAT(SALES_DATE,"%m") AS MONTH,   COUNT(DISTINCT OS.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT OS.USER_ID)/(SELECT COUNT(*) FROM SIGN_UP_AT_2021 ) ,1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS OS INNER JOIN SIGN_UP_AT_2021 AS S ON s.USER_ID = OS.USER_ID  
GROUP BY DATE_FORMAT(OS.SALES_DATE, "%Y-%m")
ORDER BY DATE_FORMAT(OS.SALES_DATE,"%Y"), DATE_FORMAT(OS.SALES_DATE,"%m")