-- 코드를 입력하세요
WITH SIGN_UP_AT_2021 AS (
    SELECT *
    FROM USER_INFO
    WHERE JOINED LIKE "2021%"
)
,
 SIGN_UP_AT_2021_COUNT AS(
    SELECT COUNT(*)
    FROM USER_INFO
    WHERE JOINED LIKE "2021%"
)

 

SELECT  DATE_FORMAT(SALES_DATE, "%Y")AS YEAR, DATE_FORMAT(SALES_DATE, "%m") AS MONTH,
COUNT(DISTINCT OS.USER_ID) AS PUCHASED_USERS, ROUND (COUNT(DISTINCT OS.USER_ID)/(SELECT *  FROM SIGN_UP_AT_2021_COUNT),1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS OS JOIN SIGN_UP_AT_2021 AS S ON s.USER_ID = OS.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH