-- 코드를 입력하세요
-- FP와 FO 테이블에서 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총 매출
SELECT FP.PRODUCT_ID,FP.PRODUCT_NAME, SUM(FO.AMOUNT) * FP.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP INNER JOIN FOOD_ORDER AS FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE DATE_FORMAT(FO.PRODUCE_DATE,"%Y-%m") LIKE "2022-05%"
GROUP BY FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC , FO.PRODUCT_ID ASC