-- 코드를 입력하세요
-- FIRST_HALF의 FLAVOR 별 TOTAL_ORDER의 합과 JULY 테이블의 TOTAL_ORDER가 큰 값
SELECT J.FLAVOR AS FLAVOR
FROM FIRST_HALF AS FH INNER JOIN JULY AS J ON FH.FLAVOR = J.FLAVOR
GROUP BY FH.FLAVOR
ORDER BY SUM(J.TOTAL_ORDER) + FH.TOTAL_ORDER DESC LIMIT 3
