-- 코드를 입력하세요
SELECT USER_ID, NICKNAME,SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER AS UU INNER JOIN USED_GOODS_BOARD AS UG ON UU.USER_ID = UG.WRITER_ID
WHERE STATUS LIKE "DONE"
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY 3