WITH getMostReivewer AS(
    SELECT *, DENSE_RANK() OVER(ORDER BY COUNT(MEMBER_ID) DESC) AS RNK
    FROM REST_REVIEW AS RR
    GROUP BY MEMBER_ID
)

# SELECT *
# FROM getMostReivewer



SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS MP INNER JOIN REST_REVIEW AS RR ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE RR.MEMBER_ID IN(SELECT MEMBER_ID FROM getMostReivewer WHERE RNK = 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT