-- 코드를 작성해주세요
# SELECT I.ID, N.FISH_NAME, I.LENGTH
# FROM FISH_INFO I
# JOIN FISH_NAME_INFO N USING(FISH_TYPE)
# WHERE FISH_TYPE IN (
#     SELECT FISH_TYPE
#     FROM FISH_INFO
#     GROUP BY FISH_TYPE
#     HAVING LENGTH = MAX(LENGTH)
# )
# ORDER BY I.ID



SELECT I.ID, N.FISH_NAME, I. LENGTH
FROM FISH_NAME_INFO N JOIN FISH_INFO I USING (FISH_TYPE)
WHERE FISH_TYPE IN(
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)
)
ORDER BY I.ID;