-- 코드를 작성해주세요

# SELECT 부서ID, 부서명, 평균연봉
# FROM HR_DEPARTMENT
# GROUP BY 부서별


SELECT HD.DEPT_ID,DEPT_NAME_EN, ROUND(AVG(SAL),0)AS AVG_SAL
FROM HR_DEPARTMENT AS HD JOIN HR_EMPLOYEES AS HE ON HD.DEPT_ID = HE.DEPT_ID
GROUP BY DEPT_ID
ORDER BY AVG_SAL DESC